# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "fastlane", "~> 2.99"

gem "cocoapods", "~> 1.5"
